### ISSUE TITLE
How bout a PR to tensorflow/swift-models?

### ISSUE THREAD

**Issue by johndpope** [BradLarson/AlexNet-Swift#1]

**Comment by BradLarson** [comment]
I've held off on this because I have a lot of custom supporting code for image loading, etc. and didn't know what kind of standard interface or layout would be desired for models in the central repository. Do I pull in just the network model and use dummy data like is done for the other models, or do I bring in all the weights, image loading code, and dataset feeding I have in here?

All of that extra code will eventually go away as those components are added to the deep learning API, so I didn't quite know what to submit. I had asked about this in the group, but people were busy leading up to the dev summit. I may ask again at some point.

**Comment by johndpope** [comment]
I see.

**Comment by johndpope** [comment]
The model class is pretty amazing (the number of computations is somehow
more apparent reading the swift code than python.) and the custom LRN model
would probably help others wanting to drop into tensorflow c++ methods.

Can always circle back and clean up code base to fit with updated
techniques.
Given that Richard and Dan helped out / I think it would be great for team
/ plus your write up would help others a lot.

I think the next mountain to climb is a GAN model. So many white papers
these days using a flavor of that. How’s your robotics? Did you ever see


Sawppy
https://github.com/Roger-random/Sawppy_Rover
